name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: 
  push:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Gather System Information
        run: |
          uname -a
          df -h
          free -m
          lscpu
          echo "-----"
          echo "Environment variables:"
          env
      - name: Gather Runner Information
        uses: actions/runner-info@v1
        id: runner_info    
      - name: Display Runner Information
        run: |
          echo "Runner Name: ${{ runner_info.outputs.name }}"
          echo "Runner Operating System: ${{ runner_info.outputs.os }}"
          echo "Runner Architecture: ${{ runner_info.outputs.arch }}"
          echo "Runner Labels: ${{ runner_info.outputs.labels }}"
          echo "Runner Work Directory: ${{ runner_info.outputs.workdir }}"
          echo "Runner Temp Directory: ${{ runner_info.outputs.tempdir }}"    
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
